# Simple Application on Windows Web App
# Package and deploy a simple web application and deploy it to Azure as Windows web app.

on:
  push:
    branches:
      - master

name: Package and deploy simple web app

jobs:
  build-and-deploy:
    runs-on: windows-2019
    steps:
    # checkout the repo
    - uses: actions/checkout@master

    # login using azure credentials
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.tiwarishubwebappwindows_950f }}

    # deploy web app
    - uses: azure/webapps-deploy@v1
      with:
        app-name: tiwarishub-webapp-windows
        package: .

    # Azure logout
    - name: logout
      run: |
        az logout